#!/bin/bash
APP=${!#}

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)

# Copy the app files
final_path=/var/www/$APP
sudo mkdir -p ${backup_dir}/var/www
sudo cp -a $final_path "${backup_dir}/var/www/$APP"

# Copy the conf files
sudo mkdir -p "${backup_dir}/conf"
sudo cp -a /etc/nginx/conf.d/$domain.d/$APP.conf "${backup_dir}/conf/nginx.conf"
sudo cp -a /etc/cron.d/$APP "${backup_dir}/conf/cron"

# Backup db
root_pwd=$(sudo cat /etc/yunohost/mysql)
sudo su -c "mysqldump -u root -p$root_pwd --no-create-db $APP > ${backup_dir}/db.sql"
