#!/bin/bash
# This restore script is adapted to Yunohost >=2.4
APP=${!#}

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

# Get old parameter of the app
domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $APP
if [[ ! $? -eq 0 ]]; then
    echo "There is already an app on this URL : $domain$path" | sudo tee /dev/stderr
    exit 1
fi

# Restore sources & data
final_path=/var/www/$APP

if [ -d $final_path ]; then
    echo "There is already a directory: $final_path " | sudo tee /dev/stderr
    exit 1
fi
sudo cp -a "${backup_dir}/var/www/$APP" $final_path

# Dependences
sudo apt-get install php5-cli -y

db_pwd=$(sudo yunohost app setting $APP mysqlpwd)
db_user=$APP
sudo yunohost app initdb $db_user -p $db_pwd
sudo su -c "mysql -u $db_user -p$db_pwd $APP < ${backup_dir}/db.sql"
sudo rm -f "${backup_dir}/db.sql"
sudo sed -i -e "s/'DB_USER', *\"[^\"]*\"/'DB_USER', \"$APP\"/g" $final_path/config.php
sudo sed -i -e "s/'DB_NAME', *\"[^\"]*\"/'DB_NAME', \"$APP\"/g" $final_path/config.php

# Set permissions
sudo chown -R www-data:www-data $final_path
for i in export images upload js
do
  sudo chmod -R 777 $final_path/cache/$i
done

for i in feed-icons lock
do
  sudo chmod -R 777 $final_path/$i
done

# Restore conf files
conf=/etc/nginx/conf.d/$domain.d/$APP.conf
if [ -f $conf ]; then
    echo "There is already a nginx conf file at this path: $conf " | sudo tee /dev/stderr
    exit 1
fi
sudo cp -a "${backup_dir}/conf/nginx.conf" $conf
sudo mv "${backup_dir}/conf/cron" /etc/cron.d/$APP
sudo chown root /etc/cron.d/$APP

# Reload Nginx
sudo service nginx reload

# Set ssowat config
sudo yunohost app setting ttrss skipped_uris -v "/public.php,/api"
sudo yunohost app ssowatconf
