#!/bin/bash
APP=${!#}

domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)

db_user=$APP
db_pwd=$(sudo yunohost app setting $APP mysqlpwd)

final_path=/var/www/$APP
sudo mkdir -p $final_path

sudo cp -a ../source/* $final_path
sudo cp ../conf/config.php $final_path/
sudo cp ../conf/*.patch /tmp/
sudo patch -d $final_path -p0 < /tmp/update.patch
sudo patch -d $final_path/plugins/auth_remote/ -p0 < /tmp/init.patch

# Change variables in ttrss configuration
sudo sed -i "s/yunouser/$db_user/g" $final_path/config.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/config.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/config.php
sudo sed -i "s,yunopath,https://$domain$path,g" $final_path/config.php

sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$APP.conf

sudo service nginx reload
sudo yunohost app ssowatconf
sudo yunohost app setting $APP skipped_uris -v "/public.php,/api"

# Update database schema
sudo su - www-data -c "$final_path/update.php --update-schema"
